site_name: 学习笔记知识库
site_url: https://Twj1108.github.io/learning-notes/

theme:
  name: material
  language: zh
  palette:
    - scheme: default
      primary: teal
      accent: teal
  features:
    - navigation.expand
    - navigation.top
    - search.highlight
    - content.code.copy

extra_css:
  - stylesheets/extra.css

plugins:
  - search

hooks:
  - hooks/tags.py

markdown_extensions:
  - admonition
  - toc:
      permalink: true
